services:
  imreddit:
    image: yokunu/imreddit:main
    container_name: imreddit_server
    hostname: imreddit_server
    ports:
      - '3000:3000'
    volumes:
      - /home/ec2-user/split_imreddit/imreddit/server/public:/home/local/app/public
    networks:
      - imreddit_net
    depends_on:
      - redis
      - nginx

  redis:
    image: redis:6.0.8
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - /usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /usr/local/etc/redis/data:/data
    networks:
      - imreddit_net
    command: redis-server /usr/local/etc/redis/redis.conf

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - '80:80'
    volumes:
      - /home/ec2-user/split_imreddit/imreddit/conf.d:/etc/nginx/conf.d
    networks:
      - imreddit_net


networks:
  imreddit_net: {}
