services:
  imreddit:
    image: imreddit:1.0
    container_name: imreddit_server
    ports:
      - '3000:3000'
    volumes:
      - /home/ec2-user/imreddit/server/public:/home/local/app/public
    networks:
      - imreddit_net
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6.0.8
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - /home/ec2-user/imreddit/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/ec2-user/imreddit/redis/data:/data
    networks:
      - imreddit_net
    command: redis-server /usr/local/etc/redis/redis.conf

  postgres:
    image: postgres:9.5.20
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    volumes:
      - /home/ec2-user/postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'imreddit'
    networks:
      - imreddit_net

networks:
  imreddit_net: {}
