services:
  imreddit:
    image: yokunu/imreddit:main
    container_name: imreddit_server
    hostname: imreddit_server
    ports:
      - '3000:3000'
    volumes:
      - ${PUBLIC_RESOURCES_DIR}:/home/local/app/public
      - ${ENVIROMENT_VARIABLES_DIR}:/home/local/app/config/env
    networks:
      - imreddit_net
    depends_on:
      - redis
      - nginx

  redis:
    image: redis:6.0.8
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - ${REDIS_CONFIG_FILE}:/usr/local/etc/redis/redis.conf
      - ${REDIS_DATA_DIR}:/data
    networks:
      - imreddit_net
    command: redis-server /usr/local/etc/redis/redis.conf

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - '80:80'
    volumes:
      - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d
    networks:
      - imreddit_net

networks:
  imreddit_net: {}
